name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer
          extensions: pdo, pdo_mysql

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Static analysis (Psalm)
        run: vendor/bin/psalm --output-format=github --no-cache

      - name: Coding style (PHP-CS-Fixer dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run tests
        run: vendor/bin/phpunit --coverage-text --colors=always
